# Generated by Django 5.1.1 on 2024-10-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания', verbose_name='Created at')),
                ('deadline', models.DateTimeField(help_text='Дедлайн', null=True, verbose_name='Deadline')),
                ('title', models.CharField(help_text='Заголовок', max_length=127, verbose_name='Title')),
                ('desc', models.TextField(help_text='Описание', null=True, verbose_name='Description')),
            ],
        ),
    ]
